  {	"Book",		"Book",		"B",		},
  {	"Book",		"Booklet",	"B",		},
  {	"Proceedings",	"Proceedings",	"",		},
  {	"Proceedings",	"Conference",	"",		},
  {	"PhDThesis",	"PhdThesis",	"D",		},
  {	"TechReport",	"TechReport",	"R",		},
  {	"TechReport",	"Manual",	"R",		},
  {	"MastersThesis","MastersThesis","D",		},
  {	"Misc",		"Misc", 	"O",		},
  {	"Misc",		"Unpublished", 	"",		},
  {	"Article",	"Article",	"J",		},
  {	"InBook",	"InBook",	"P",		},
  {	"InBook",	"InCollection",	"P",		},
  {	"InProceedings","InProceedings","C",	






  {	"@Type",	"typ",		"TYPE",		},
  {	"@Tag",		"tag",		"NUMBER",	},
  {	"@Abstract",	"",		"",		},
  {	"@Address",	"address",	"",		},
  {	"@Annote",	"annote",	"PROBLEM",	},
  {	"@Author",	"author",	"AUTHOR",	},
  {	"",		"chapter",	"",		},
  {	"@Day",		"",		"",		},
  {	"@Edition",	"edition",	"",		},
  {	"@HowPublished","howpublished",	"",		},
  {	"@InAuthor",	"editor",	"",		},
  {	"@InTitle",	"booktitle",	"",		},
  {	"@Institution",	"institution",	"INSTIT",	},
  {	"@Journal",	"journal",	"SOURCE",	},
  {	"",		"key",		"",		},
  {	"@Keywords",	"",		"",		},
  {	"@Label",	"",		"",		},
  {	"@Month",	"month",	"",		},
  {	"@Note",	"note",		"",		},
  {	"@Number",	"number",	"ISSUE",	},
  {	"@Organization","organization",	"",		},
  {	"@Pages",	"pages",	"FIRSTPAGE",	},
  {	"@Page",	"pages",	"",		},
  {	"@Pinpoint",	"",		"",		},
  {	"@Publisher",	"publisher",	"PUBLISHER",	},
  {	"@Title",	"title",	"NAME",		},
  {	"@TitleNote",	"",		"",		},
  {	"@TRType",	"type",		"",		},
  {	"@URL",		"url",		"",		},
  {	"@Volume",	"volume",	"VOL",		},
  {	"@Year",	"year", 	"YEAR",		},
