#!/opt/exp/bin/tclsh
#  -*-Tcl-*- for (X)emacs ##


### USAGE:
#   ln -s /home/ggreif/aL4nin/purgatory/clear-c DIR/clear-c
#   ln -s /home/ggreif/aL4nin/purgatory/clear-c DIR/clear-m
#   ln -s /home/ggreif/aL4nin/purgatory/clear-c DIR/clear-a
#   ln -s /home/ggreif/aL4nin/purgatory/clear-c DIR/clear-l
#   rm ./Version.o makefile ; gmake -f Makefile EXEC=omega \
#        GHC="ghc -O -pgmc clear-c -pgmm clear-m -pgma clear-a -pgml clear-l"

## SEE: http://www.haskell.org/ghc/docs/latest/html/users_guide/options-phases.html

puts "\#\#\# argv0 = $argv0"

proc find-o { } {
    global argv

    if [llength $argv]==2 {
	puts stderr "OUT2: [lindex $argv 1]\n"
	return [lindex $argv 1]
    }

    set flag ""

    foreach i $argv {
	puts stderr "\#\#\#\#\#\#\#\# $i $flag\n"
	if [string equal "" $flag] {
	puts stderr "WOOOO $i\n"
	    if [string equal $i "-o"] {
		set flag $i
	puts stderr "POOOO $flag\n"
	    }
	} else {
	puts stderr "HEY $flag    ---> $i\n"
	    switch -exact -- $flag {
		-o { set out $i }
	    }
	    set flag ""
	}
    }

	puts stderr "OUT: $out\n"
    return $out
}

set mak [open "makefile" a]
puts $mak "$argv"
puts $mak "OUTFILE is [find-o]"
close $mak

exec touch ./Version.hs
exec touch ./Toplevel.hs

