foreach login {ftd guest gardener ohmega yang howie hmonk bbarker} {

    foreach pass {airplane alphabet aviator bidirectional changeme creosote cyclone december dolphin elephant ersatz} {
	
	# puts "$login $pass"
	spawn "./terra-incognita"
	expect {
	    -timeout 300 "login: " {
		send "$login\r"
		expect {
		    -timeout 10 "password: " {
#			puts "WOW"
			send "$pass\r" 
			expect {
			    -timeout 20 "logged in as" { puts "YEP: $login $pass" }
			}
		    }
		}
	    }
	}
	exp_close $spawn_id
    }
}
