foreach login {ftd guest gardener ohmega yang howie hmonk bbarker} {

foreach pass {airplane alphabet aviator bidirectional changeme creosote cyclone december dolphin elephant ersatz} {

# puts "$login $pass"
spawn "./terra-incognita"
expect {
  -timeout 300 "login: " {
	send "$login\r"
        expect { "password:" {
			send "$pass\r" 
			expect { "logged in as" { puts "YEP: $login $pass" }
			}
		    }
		}
	}
}

}
}
