terra-incognita: terra-incognita.lid terra-incognita.dylan terra-incognita-exports.dylan um-spec.dylan
	d2c terra-incognita.lid

clean:
	-rm -f *.o *.s *.a *.c *.mak *~ terra-incognita
	-rm -rf .libs
